[package]
name = "mailbox_processor"
version = "0.3.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "rt", "macros", "time"] }

[dev-dependencies]
tokio-test = "0.4"
